### ISSUE TITLE
Totally failed on Firefox Linux Mint

### ISSUE THREAD

**Issue by worikgh** [a-sumo/hyperstep#1]
Firefox: 105.0.3 (64-bit)

uname -a
Linux munroe 5.4.0-128-generic #144-Ubuntu SMP Tue Sep 20 11:00:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Looking at the browser console the error is:

`An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page.`

Web app programming is not my thing but happy to dig deeper if you have any instructions

**Comment by a-sumo** [comment]
Thank you for the feedback, I'm investigating an issue related to the Web Audio API on Linux. 
I don't have access to a Linux partition right now, so while I setup one I recommend you to try the website on a smartphone, preferably with a small audio snippet.

**Comment by a-sumo** [comment]
I have attempted to fix the AudioContext initialization issue, let me know if there are any changes.
